cpuCore = 4
memory = 2
hostname = "ANSIBLE-001"

template = File.read("../DEBIAN-12/Vagrantfile.template")
eval(template)

shared_folder_local = '\\\\wsl.localhost\Ubuntu\home\tristiisch\dev\devops\ansible'
shared_folder_remote = "/opt/data"
shared_folder_name = "data"
shared_folder_owner = username
shared_folder_group = username
shared_folder_mask = 077

SKIP_PROVISIONERS = true

Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: <<-SHELL
  	sudo apt update
    sudo apt install -y ansible make
  SHELL

  config.vm.provider "vmware_desktop" do |vmware, override|

    override.vm.synced_folder shared_folder_local, shared_folder_remote,
      id: shared_folder_name,
      owner: shared_folder_owner,
      group: shared_folder_group,
      mount_options: ["umask=#{shared_folder_mask}"]

  end
end
