Vagrant.configure("2") do |config|
  config.vm.box = "packer_DEBIAN-12_vmware.box"

  config.vm.provision "shell", inline: <<-SHELL
  	sudo apt update
    sudo apt install -y ansible make
  SHELL

  cpuCore = 2
  memory = 2
  hostname = "ANSIBLE-001"
  username = "president"
  password = "P@ssword!"

  config.vm.hostname = hostname
  config.vm.communicator = "ssh"
  config.ssh.username = username
  config.ssh.password = password
  config.ssh.keep_alive = true
  config.ssh.disable_deprecated_algorithms = true

  config.vm.synced_folder "./vagrant/", "/vagrant", disabled: true

  config.vm.provider "vmware_desktop" do |vmware, override|
    vmware.gui = true
    # VMWare link or deep copy
    vmware.linked_clone = false
    # VMWare name on library
    vmware.vmx["displayName"] = hostname

    # Number of CPU cores
    vmware.vmx["cpuid.coresPerSocket"] = cpuCore
    # Number of CPUs (need to multiply the value by 4)
    vmware.vmx["numvcpus"] = (1 * 4)
    # Memory in MB (var memory is in GB, then we convert to MB)
    vmware.vmx["memsize"] = memory * 1024

    vmware.vmx["ethernet0.vnet"] = "VMnet8"
    vmware.vmx["ethernet0.connectiontype"] = "custom"
    vmware.vmx["ethernet0.displayName"] = "VMnet8"
    vmware.vmx["ethernet0.virtualdev"] = "e1000e"
	vmware.vmx["ethernet0.pcislotnumber"] = "160"

	override.vm.synced_folder "./data/", "/opt/data", id: "data", owner: "president", group: "president", mount_options: ["umask=077"]

    # Enable Virtualize usage in VM - Need to disable Hyper-V on Host to work
    vmware.vmx["vhv.enable"] = false

    # Virtualize CPU performance counter
    vmware.vmx["vpmc.enable"] = false

    # Allow shared folders between Host & Guest
    vmware.vmx["isolation.tools.hgfs.disable"] = true

	# Unmount the default HGFS mount point within the guest
    # vmware.unmount_default_hgfs = true
  end
end
